### ISSUE TITLE
snapshot mode problem

### ISSUE THREAD

**Issue by slackworker** [pH5/ouvrt#1]
Hi friend,
    I got a problem during debug mt9v034 snapshot mode in another project . And see you code have used snapshot mode, I'd like to ask if you have the same problem.

    Firstly I initialize the sensor, set the sensor to snapshot mode (r0x07set to 0x0398), 
    and turn off  aec / agc function (r0xaf set to 0x0000).
    Then give trigger pulse to ex-posure pin and read out an image.

The problem is:
    When the trigger cycle less than about 0.5s, the read out image looks more normal,
    When the trigger interval is growing,   the image appears more and more white(color) noise, (See attachment) 
    When the trigger interval time reaches a few minutes, the image is basically a white paper.

In addition, through observation and experiment also found:
    1, the location of the noise completely fixed.
    2, in the idle time period standby sensor can not solve this problem.
    3, from the point of view, like in the idle time, sensor has been exposed, 
        but by observing led_out pin we found exposure time is correct.
    4, I tried similar initialization code in your “int mt9v034_sensor_enable_sync (int fd)” function , get the same result.

So I submit the issue to ask for your help.

Looking forward to your reply, thx!~

0.5s
![0 5s](https://user-images.githubusercontent.com/7830149/29704543-e1a3a9b6-89ac-11e7-9ada-d43076b4c05c.jpg)
1s
![1s](https://user-images.githubusercontent.com/7830149/29704548-e1aa53d8-89ac-11e7-95ab-45d2bdbb24d0.jpg)
2s
![2s](https://user-images.githubusercontent.com/7830149/29704544-e1a458de-89ac-11e7-8d1f-92c2bd3c1cba.jpg)
5s
![5s](https://user-images.githubusercontent.com/7830149/29704545-e1a4d494-89ac-11e7-9476-46625cfb8909.jpg)
10s
![10s](https://user-images.githubusercontent.com/7830149/29704547-e1a7de6e-89ac-11e7-920f-b4dd80bccab3.jpg)
30s
![30s](https://user-images.githubusercontent.com/7830149/29704546-e1a51544-89ac-11e7-9b85-2a9aee91d606.jpg)
60s
![60s](https://user-images.githubusercontent.com/7830149/29704549-e1cf97c4-89ac-11e7-8922-93b62c9f240a.jpg)
600s
![600s](https://user-images.githubusercontent.com/7830149/29704550-e1d800f8-89ac-11e7-9fc4-aee1beacaf2f.jpg)
Related video
[20170825154727.zip](https://github.com/pH5/ouvrt/files/1251186/20170825154727.zip)

**Comment by pH5** [comment]
I have no experience with this kind of behavior. It looks to me like the black level signal could be too high. According to the signal path figure in the data sheet, there is an offset correction voltage added to the pixel output before gain and ADC (configured via register 0x48 or BLC output). Maybe try reducing that? Also check if the ADC voltage reference is configured correctly.
