### ISSUE TITLE
Samsung Odyssey plus gstreamer weird image, pipewire working fine

### ISSUE THREAD

**Issue by johnr14** [pH5/ouvrt#3]
Tried on a Samsung Odyssey plus. Build with gstreamer and  pipewire disabled. 

```
udev: Found HoloLens Sensors: /dev/bus/usb/008/003
HoloLens Sensors: Serial e146fa9d-fd47-4b81-97cd-11745667db51
HoloLens Sensors: USB3
HoloLens Sensors: acquired new id 0 for serial e146fa9d-fd47-4b81-97cd-11745667db51
ouvrtd: Acquired session bus, name: 'de.phfuenf.ouvrt.Ouvrtd'
ouvrtd: Acquired name "de.phfuenf.ouvrt.Ouvrtd"
HoloLens Sensors: Missing frame: 0 -> 25
debug: connected
debug: disconnected
```
![Odysseyplus](https://user-images.githubusercontent.com/5272079/72774854-20f41d80-3bda-11ea-9457-603b5a283090.png)

I recompilled with gstreamer disabled and pipewire enabled and it works. 

```
udev: Found HoloLens Sensors: /dev/bus/usb/008/003
HoloLens Sensors: Serial e146fa9d-fd47-4b81-97cd-11745667db51
HoloLens Sensors: USB3
HoloLens Sensors: acquired new id 0 for serial e146fa9d-fd47-4b81-97cd-11745667db51
ouvrtd: Acquired session bus, name: 'de.phfuenf.ouvrt.Ouvrtd'
ouvrtd: Acquired name "de.phfuenf.ouvrt.Ouvrtd"
HoloLens Sensors: Missing frame: 0 -> 25

```

![odyssey-gstreamer](https://user-images.githubusercontent.com/5272079/72777059-58ff5e80-3be2-11ea-8f39-2689ad1dae6b.png)

There seems to be always missing frames 0->25.

**Edit:**
The first stream is 30 fps and works fine for gray video.
The second stream is 60 fps and is for tracking the controllers as it will only show bright led.
Seems like second stream could track PS move controllers !

Thanks for your work !
But still can't get O+ to display with openhmd.

**Comment by pH5** [comment]
Thank you for testing. Most probably the weird GStreamer image is caused by providing an incorrectly set frame size for this camera. The [shmsrc element](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad/html/gst-plugins-bad-plugins-shmsrc.html) can not negotiate resolution with the sender and believes anything it is told on the command line. This should work correctly, for example:

```
#!/bin/sh
gst-launch-1.0 \
	shmsrc socket-path=/tmp/ouvrtd-gst-0 ! \
	video/x-raw,format=GRAY8,width=1280,height=481,framerate=30/1 ! \
	videoconvert ! autovideosink \
	shmsrc socket-path=/tmp/ouvrtd-gst-1 ! \
	video/x-raw,format=GRAY8,width=1280,height=481,framerate=60/1 ! \
	videoconvert ! autovideosink
```

**Comment by johnr14** [comment]
I can confirm that it works with the above command line.
With the O+, a gain of >90 gives better results.
The controller frame is too dark to track controllers, it works with cellphone.

**Q:**
Is your magic 6000 the same as 		
`.unknown_6000 = __cpu_to_le16(0x1770),`
as I tried it out and it makes no change and the camera gains can still be adjusted.
I tried 0x13b0 and others with no success.

Thanks.
**EDIT You may add Samsung Odyssey + on your working device list.**

**Comment by pH5** [comment]
Yes, the `70 17` (6000) is the only number that appeared in my logs at this place. Changing it didn't have any visible effect.
